update unit test

diff --git a/.github/workflows/deployment.yml b/.github/workflows/deployment.yml
--- a/.github/workflows/deployment.yml
+++ b/.github/workflows/deployment.yml
@@ -26,6 +26,39 @@ jobs:
         run: |
           docker build -f Dockerfile.prod -t back-img .
 
+  # test:
+  #   name: xUnit Testing
+  #   needs: build
+  #   runs-on:
+  #     labels: ["self-hosted", "Linux", "X64", "back-runner"]
+  #   container:
+  #     image: mcr.microsoft.com/dotnet/sdk:8.0
+  #   steps:
+  #     - name: Configure Git safe directory
+  #       run: |
+  #        git config --global --add safe.directory /__w/studymate-backend/studymate-backend
+  #     - name: Checkout code
+  #       uses: actions/checkout@v4
+  #     - name: Restore dependencies
+  #       run: dotnet restore
+  #     - name: Build the project
+  #       run: dotnet build --no-restore
+  #     - name: Test
+  #       run: dotnet test --no-build --verbosity normal 
+  #     - name: Test Report
+  #       uses: dorny/test-reporter@v1
+  #       if: success() || failure()
+  #       with:
+  #         name: .NET xUnit Test
+  #         path: "**/test-results.trx"
+  #         reporter: dotnet-trx
+  #         fail-on-error: true
+  #         fail-on-empty: false
+  #     - name: cleaning project
+  #       run: |
+  #         rm -rf bin/
+  #         rm -rf obj/
+          
   test:
     name: xUnit Testing
     needs: build
@@ -36,21 +69,21 @@ jobs:
     steps:
       - name: Configure Git safe directory
         run: |
-         git config --global --add safe.directory /__w/studymate-backend/studymate-backend
+          git config --global --add safe.directory /__w/studymate-backend/studymate-backend
       - name: Checkout code
         uses: actions/checkout@v4
       - name: Restore dependencies
-        run: dotnet restore
+        run: dotnet restore studymate-backend.sln
       - name: Build the project
-        run: dotnet build --no-restore
+        run: dotnet build studymate-backend.sln --no-restore
       - name: Test
-        run: dotnet test --no-build --verbosity normal 
-      - name: Test Report
-        uses: dorny/test-reporter@v1
+        run: dotnet test ./Tests/Tests.csproj --logger "trx" --no--build --verbosity normal 
+      - name: Test Reporter
+        uses: dorny/test-reporter@v1.9.1
         if: success() || failure()
         with:
           name: .NET xUnit Test
-          path: "**/test-results.trx"
+          path: "**/*.trx"
           reporter: dotnet-trx
           fail-on-error: true
           fail-on-empty: false
@@ -58,32 +91,6 @@ jobs:
         run: |
           rm -rf bin/
           rm -rf obj/
-          
-  # test:
-  # name: xUnit Testing
-  # needs: build
-  # runs-on:
-  #   labels: ["self-hosted", "Linux", "X64", "back-runner"]
-  # container:
-  #   image: mcr.microsoft.com/dotnet/sdk:8.0
-  # steps:
-  #   - name: Checkout code
-  #     uses: actions/checkout@v4
-  #   - name: Restore dependencies
-  #     run: dotnet restore studymate-backend.sln
-  #   - name: Build the project
-  #     run: dotnet build studymate-backend.sln --no-restore
-  #   - name: Test
-  #     run: dotnet test ./Tests/Tests.csproj --no--build --verbosity normal 
-  #   - name: Test Report
-  #     uses: dorny/test-reporter@v1
-  #     if: success() || failure()
-  #     with:
-  #       name: .NET xUnit Test
-  #       path: "**/test-results.trx"
-  #       reporter: dotnet-trx
-  #       fail-on-error: true
-  #       fail-on-empty: false
 
   sonarqube:
     name: SonarQube Analyze
