test sonarqube error

diff --git a/.github/workflows/deployment.yml b/.github/workflows/deployment.yml
--- a/.github/workflows/deployment.yml
+++ b/.github/workflows/deployment.yml
@@ -12,45 +12,45 @@ on:
 run-name: "${{ contains(github.head_ref, 'feature/') && 'Feature' || contains(github.head_ref, 'bugfix/') && 'Bugfix' || 'Update' }}: ${{ github.head_ref }} by @${{ github.actor }}"
 
 jobs:
-  build:
-    name: Build
-    runs-on:
-      labels: ["self-hosted", "Linux", "X64", "back-runner"]
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v2
+  # build:
+  #   name: Build
+  #   runs-on:
+  #     labels: ["self-hosted", "Linux", "X64", "back-runner"]
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v4
+  #     - name: Set up Docker Buildx
+  #       uses: docker/setup-buildx-action@v2
 
-      - name: Build Docker Image
-        run: |
-          docker build -f Dockerfile.prod -t back-img .
+  #     - name: Build Docker Image
+  #       run: |
+  #         docker build -f Dockerfile.prod -t back-img .
 
-  test:
-    name: xUnit Testing
-    needs: build
-    runs-on:
-      labels: ["self-hosted", "Linux", "X64", "back-runner"]
-    container:
-      image: mcr.microsoft.com/dotnet/sdk:8.0
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-      - name: Restore dependencies
-        run: dotnet restore
-      - name: Build the project
-        run: dotnet build --no-restore
-      - name: Test
-        run: dotnet test --no-build --verbosity normal 
-      - name: Test Report
-        uses: dorny/test-reporter@v1
-        if: success() || failure()
-        with:
-          name: .NET xUnit Test
-          path: "**/test-results.trx"
-          reporter: dotnet-trx
-          fail-on-error: true
-          fail-on-empty: false
+  # test:
+  #   name: xUnit Testing
+  #   needs: build
+  #   runs-on:
+  #     labels: ["self-hosted", "Linux", "X64", "back-runner"]
+  #   container:
+  #     image: mcr.microsoft.com/dotnet/sdk:8.0
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v4
+  #     - name: Restore dependencies
+  #       run: dotnet restore
+  #     - name: Build the project
+  #       run: dotnet build --no-restore
+  #     - name: Test
+  #       run: dotnet test --no-build --verbosity normal 
+  #     - name: Test Report
+  #       uses: dorny/test-reporter@v1
+  #       if: success() || failure()
+  #       with:
+  #         name: .NET xUnit Test
+  #         path: "**/test-results.trx"
+  #         reporter: dotnet-trx
+  #         fail-on-error: true
+  #         fail-on-empty: false
     # test:
     # name: xUnit Testing
     # needs: build
@@ -79,7 +79,7 @@ jobs:
 
   sonarqube:
     name: SonarQube Analyze
-    needs: test
+    # needs: test
     runs-on: ["self-hosted", "org-runner"]
     container:
       image: mcr.microsoft.com/dotnet/sdk:8.0
