update deployment file

diff --git a/.github/workflows/deployment.yml b/.github/workflows/deployment.yml
--- a/.github/workflows/deployment.yml
+++ b/.github/workflows/deployment.yml
@@ -12,70 +12,70 @@ on:
 run-name: "${{ contains(github.head_ref, 'feature/') && 'Feature' || contains(github.head_ref, 'bugfix/') && 'Bugfix' || 'Update' }}: ${{ github.head_ref }} by @${{ github.actor }}"
 
 jobs:
-  # build:
-  #   name: Build
-  #   runs-on:
-  #     labels: ["self-hosted", "Linux", "X64", "back-runner"]
-  #   steps:
-  #     - name: Checkout code
-  #       uses: actions/checkout@v4
-  #     - name: Set up Docker Buildx
-  #       uses: docker/setup-buildx-action@v2
+  build:
+    name: Build
+    runs-on:
+      labels: ["self-hosted", "Linux", "X64", "back-runner"]
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v2
 
-  #     - name: Build Docker Image
-  #       run: |
-  #         docker build -f Dockerfile.prod -t back-img .
+      - name: Build Docker Image
+        run: |
+          docker build -f Dockerfile.prod -t back-img .
 
+  test:
+    name: xUnit Testing
+    needs: build
+    runs-on:
+      labels: ["self-hosted", "Linux", "X64", "back-runner"]
+    container:
+      image: mcr.microsoft.com/dotnet/sdk:8.0
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+      - name: Restore dependencies
+        run: dotnet restore
+      - name: Build the project
+        run: dotnet build --no-restore
+      - name: Test
+        run: dotnet test --no-build --verbosity normal 
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()
+        with:
+          name: .NET xUnit Test
+          path: "**/test-results.trx"
+          reporter: dotnet-trx
+          fail-on-error: true
+          fail-on-empty: false
   # test:
-  #   name: xUnit Testing
-  #   needs: build
-  #   runs-on:
-  #     labels: ["self-hosted", "Linux", "X64", "back-runner"]
-  #   container:
-  #     image: mcr.microsoft.com/dotnet/sdk:8.0
-  #   steps:
-  #     - name: Checkout code
-  #       uses: actions/checkout@v4
-  #     - name: Restore dependencies
-  #       run: dotnet restore
-  #     - name: Build the project
-  #       run: dotnet build --no-restore
-  #     - name: Test
-  #       run: dotnet test --no-build --verbosity normal 
-  #     - name: Test Report
-  #       uses: dorny/test-reporter@v1
-  #       if: success() || failure()
-  #       with:
-  #         name: .NET xUnit Test
-  #         path: "**/test-results.trx"
-  #         reporter: dotnet-trx
-  #         fail-on-error: true
-  #         fail-on-empty: false
-    # test:
-    # name: xUnit Testing
-    # needs: build
-    # runs-on:
-    #   labels: ["self-hosted", "Linux", "X64", "back-runner"]
-    # container:
-    #   image: mcr.microsoft.com/dotnet/sdk:8.0
-    # steps:
-    #   - name: Checkout code
-    #     uses: actions/checkout@v4
-    #   - name: Restore dependencies
-    #     run: dotnet restore studymate-backend.sln
-    #   - name: Build the project
-    #     run: dotnet build studymate-backend.sln --no-restore
-    #   - name: Test
-    #     run: dotnet test ./Tests/Tests.csproj --no--build --verbosity normal 
-    #   - name: Test Report
-    #     uses: dorny/test-reporter@v1
-    #     if: success() || failure()
-    #     with:
-    #       name: .NET xUnit Test
-    #       path: "**/test-results.trx"
-    #       reporter: dotnet-trx
-    #       fail-on-error: true
-    #       fail-on-empty: false
+  # name: xUnit Testing
+  # needs: build
+  # runs-on:
+  #   labels: ["self-hosted", "Linux", "X64", "back-runner"]
+  # container:
+  #   image: mcr.microsoft.com/dotnet/sdk:8.0
+  # steps:
+  #   - name: Checkout code
+  #     uses: actions/checkout@v4
+  #   - name: Restore dependencies
+  #     run: dotnet restore studymate-backend.sln
+  #   - name: Build the project
+  #     run: dotnet build studymate-backend.sln --no-restore
+  #   - name: Test
+  #     run: dotnet test ./Tests/Tests.csproj --no--build --verbosity normal 
+  #   - name: Test Report
+  #     uses: dorny/test-reporter@v1
+  #     if: success() || failure()
+  #     with:
+  #       name: .NET xUnit Test
+  #       path: "**/test-results.trx"
+  #       reporter: dotnet-trx
+  #       fail-on-error: true
+  #       fail-on-empty: false
 
   sonarqube:
     name: SonarQube Analyze
@@ -151,7 +151,7 @@ jobs:
 
       - name: Build and analyze
         run: |
-          .sonar/scanner/dotnet-sonarscanner begin /k:"kmitl-savvy-students_studymate-backend_9cb6e3af-69ca-4169-ab00-b313f0119e1e" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="${{ secrets.SONAR_HOST_URL }}"
+          .sonar/scanner/dotnet-sonarscanner begin /k:"kmitl-savvy-students_studymate-backend_9cb6e3af-69ca-4169-ab00-b313f0119e1e" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="${{ secrets.SONAR_HOST_URL }}" /d:sonar.sources="." /d:sonar.tests="./Tests"
           dotnet build
           .sonar/scanner/dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
           
